language: node_js
node_js:
  - "12.16"

#unhappyly the worst happened - an infinite build-push-trigger loop
#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  keep-history: true
#  target-branch: master
#  on:
#    branch: master

after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    #configure
    git config user.name "deploy@travis-ci.org"
    git config user.email "Deployment User Script"
    #
    git checkout -q master
    #list of staged files
    git add -f apps/*
    #
    git commit -m "Travis update: `date "+%b %Y"` (Build $TRAVIS_BUILD_NUMBER)" -m "[skip ci]"

    # push only if "git commit" succeeded
    if [ $? -eq 0 ]; then
      echo "pushing...."
      git remote rm origin
      git remote add origin https://henriquericcio:${GH_TOKEN}@github.com/codingzenorg/site.git > /dev/null 2>&1
      git push origin master --quiet
    else
      echo "No changes. Nothing to do"
    fi
  fi
